remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Machine Learning pour les séries temporelles en Python"
description: "Tutoriel organisé dans le cadre de la conférence CAp 2023"
